### ISSUE TITLE
Fatal:  invalid refspec 'master'?

### ISSUE THREAD

**Issue by filiptronicek** [gelstudios/gitfiti#77]
It seems when I try to run the bash script in Ubuntu's Terminal, it creates the repo, but then fails at `Fatal:  invalid refspec 'master'?`.

**Comment by gelstudios** [comment]
Can you run `git branch -a` and post the result? The script probably needs the default branch name changed from "master" to "main".

**Comment by grabtheskills** [comment]
![Screen Shot 2020-11-09 at 4 45 56 pm](https://user-images.githubusercontent.com/57908912/98518950-10b54800-22ab-11eb-8245-7cacbd6ff04d.png)

Im going trough the same problem, it keeps on showing **fatal: couldn't find remote ref master**

**git branch -a** showing me as above screenshot.  Is there any problem with my git ? Thanks for your help !

**Comment by gelstudios** [comment]
It turns out that the local git default is still "master", so the `git branch -a` output is right. 

Github is now using "main" as the default base branch for new repositories, so gitfiti has been updated to use the new default.

I also moved this repo's base branch to main.

If you run into similar issues, deleting the target repo and re-creating it on github should make it work.

**Comment by gelstudios** [comment]
@grabtheskills it looks like your error was different, and is likely an auth problem.
`git@github.com: Permission denied (publickey).`

you could try deleting the target repo from github and created it again.
you might also want to make sure your name / email as displayed in `git config -l` match your github profile, or the commits / pixels wont be attributed to your profile.
